keyword_categorization = [
# Grocery Store
("egg","grocery"),
("milk","grocery"),
("strawberry","grocery"),
("chips","grocery"),
("coke","grocery"),
("shampoo","grocery"),
("soap","grocery"),
("band-aid","grocery"),
("red-bull","grocery"),
("juice","grocery"),
("wine","grocery"),
("bread","grocery"),
("q-tips","grocery"),
("water","grocery"),
("peanut-butter","grocery"),
("chocolate","grocery"),
("candy","grocery"),
("food","grocery"),
("eggplant","grocery"),
("apple","grocery"),
("orange","grocery"),
("pear","grocery"),
("banana","grocery"),
("watermelon","grocery"),
("tomato","grocery"),
("kiwi","grocery"),
("pineapple","grocery"),
("Cheerios","grocery"),
("ice-cream","grocery"),
("Mozarella","grocery"),
("nutella","grocery"),
("sprite","grocery"),
("napkins","grocery"),
("doritos","grocery"),
("pop-tarts","grocery"),
("deodorant","grocery"),
("lotion","grocery"),
("cheese","grocery"),
("yogurt","grocery"),
("pudding","grocery"),
("cake","grocery"),
("cookies","grocery"),
("icebreakers","grocery"),
("mints","grocery"),

# Electronics
("charger","electronics"),
("phone","electronics"),
("iphone","electronics"),
("television","electronics"),
("speakers","electronics"),
("DVD","electronics"),
("video","electronics"),
("android","electronics"),
("cable","electronics"),
("video","electronics"),


#Restaurants
("sandwiches","restaurants"),
("pizza","restaurants"),
("cuisine","restaurants"),
("restaurants","restaurants"),
("pasta","restaurants"),
("mexican","restaurants"),
("pad-thai","restaurants"),

#Clothing
("jeans","Clothing Apparel"),
("suit","Clothing Apparel"),
("jersey","Clothing Apparel"),
("shoes","Clothing Apparel"),
("shorts","Clothing Apparel"),
("dress","Clothing Apparel"),
("boxers","Clothing Apparel"),
("socks","Clothing Apparel"),
("dress-shoes","Clothing Apparel"),
("belt","Clothing Apparel"),
("shoelace","Clothing Apparel"),
("buttons","Clothing Apparel"),
("cardigan","Clothing Apparel"),
("sweater","Clothing Apparel"),
("turban","Clothing Apparel"),
("jacket","Clothing Apparel"),
("coat","Clothing Apparel"),
("dress-shirt","Clothing Apparel"),

#Sports Equipment
("tennis","sporting goods"),
("soccer","sporting goods"),
("football","sporting goods"),
("basketball","sporting goods"),
("cleats","sporting goods"),
("baseball","sporting goods"),
("golf","sporting goods"),
("helmet","sporting goods"),
("kayak","sporting goods"),
("shinguard","sporting goods"),
("jersey","sporting goods"),
("rifle","sporting goods"),
("fishing-rod","sporting goods"),
("goal","sporting goods"),

# Miscellaneous
("deposit","bank"),
("withdrawal","bank"),
("mail", "post office")
]